app = "cinecornetabot-main-1"
primary_region = "gru"

[env]
DB_PATH = "/data/pedidos.db"

[mounts]
source = "data"
destination = "/data"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 10_000
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"